//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncDecFile.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EncDecFile.Language.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        internal static string _in {
            get {
                return ResourceManager.GetString("in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string.
        /// </summary>
        internal static string _string {
            get {
                return ResourceManager.GetString("string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto encrypt or decrypt filename.
        /// </summary>
        internal static string a_opt_desc {
            get {
                return ResourceManager.GetString("a_opt_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If filename is encrypted it is decrypted, and if it is plain text it is encrypted.
        /// </summary>
        internal static string a_opt_desc2 {
            get {
                return ResourceManager.GetString("a_opt_desc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string action {
            get {
                return ResourceManager.GetString("action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic detection (not reliable).
        /// </summary>
        internal static string automatic_detection {
            get {
                return ResourceManager.GetString("automatic_detection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created output file.
        /// </summary>
        internal static string created_output_file {
            get {
                return ResourceManager.GetString("created_output_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypts config file filename.
        /// </summary>
        internal static string d_opt_desc {
            get {
                return ResourceManager.GetString("d_opt_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypted.
        /// </summary>
        internal static string decrypted {
            get {
                return ResourceManager.GetString("decrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypted String.
        /// </summary>
        internal static string decrypted_string {
            get {
                return ResourceManager.GetString("decrypted_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypting.
        /// </summary>
        internal static string decrypting {
            get {
                return ResourceManager.GetString("decrypting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypts config file filename.
        /// </summary>
        internal static string e_opt_desc {
            get {
                return ResourceManager.GetString("e_opt_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ( [E]ncrypt | [D]ecrypt | [O]ther ).
        /// </summary>
        internal static string encrypt_decrypt {
            get {
                return ResourceManager.GetString("encrypt_decrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted.
        /// </summary>
        internal static string encrypted {
            get {
                return ResourceManager.GetString("encrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted String.
        /// </summary>
        internal static string encrypted_string {
            get {
                return ResourceManager.GetString("encrypted_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypting.
        /// </summary>
        internal static string encrypting {
            get {
                return ResourceManager.GetString("encrypting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating output file.
        /// </summary>
        internal static string error_creating_output_file {
            get {
                return ResourceManager.GetString("error_creating_output_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing file.
        /// </summary>
        internal static string error_processing_file {
            get {
                return ResourceManager.GetString("error_processing_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist.
        /// </summary>
        internal static string file_does_not_exist {
            get {
                return ResourceManager.GetString("file_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filename.
        /// </summary>
        internal static string filename {
            get {
                return ResourceManager.GetString("filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished processing file.
        /// </summary>
        internal static string finished_processing_file {
            get {
                return ResourceManager.GetString("finished_processing_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished processing string.
        /// </summary>
        internal static string finished_processing_string {
            get {
                return ResourceManager.GetString("finished_processing_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found.
        /// </summary>
        internal static string found {
            get {
                return ResourceManager.GetString("found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From a total of.
        /// </summary>
        internal static string from_a_total_of {
            get {
                return ResourceManager.GetString("from_a_total_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file.
        /// </summary>
        internal static string input_file {
            get {
                return ResourceManager.GetString("input_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing value for the option.
        /// </summary>
        internal static string missing_option {
            get {
                return ResourceManager.GetString("missing_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to be part of the gudepssii to run this programme.
        /// </summary>
        internal static string need_to_be_group_gudepssii {
            get {
                return ResourceManager.GetString("need_to_be_group_gudepssii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write output to outputfile.
        /// </summary>
        internal static string o_opt_desc {
            get {
                return ResourceManager.GetString("o_opt_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If no outputfile is given with -o, the output file will be auto named.
        /// </summary>
        internal static string o_opt_desc2 {
            get {
                return ResourceManager.GetString("o_opt_desc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string options {
            get {
                return ResourceManager.GetString("options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output File:.
        /// </summary>
        internal static string output_file {
            get {
                return ResourceManager.GetString("output_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file already exists, aborting.
        /// </summary>
        internal static string output_file_already_exists {
            get {
                return ResourceManager.GetString("output_file_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to outputfile .
        /// </summary>
        internal static string outputfile {
            get {
                return ResourceManager.GetString("outputfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter error.
        /// </summary>
        internal static string parameter_error {
            get {
                return ResourceManager.GetString("parameter_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path is a directory, should be a filename.
        /// </summary>
        internal static string path_is_a_directory_should_be_a_filename {
            get {
                return ResourceManager.GetString("path_is_a_directory_should_be_a_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission denied.
        /// </summary>
        internal static string permision_denied {
            get {
                return ResourceManager.GetString("permision_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        internal static string processing {
            get {
                return ResourceManager.GetString("processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program to encrypt or decrypt a dotnet .config configuration file..
        /// </summary>
        internal static string progdesc {
            get {
                return ResourceManager.GetString("progdesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt and Decrypt string, print output to standard output.
        /// </summary>
        internal static string s_opt_desc {
            get {
                return ResourceManager.GetString("s_opt_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Help .
        /// </summary>
        internal static string see_usage {
            get {
                return ResourceManager.GetString("see_usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tried to decrypt non encrypted.
        /// </summary>
        internal static string tried_decrypt {
            get {
                return ResourceManager.GetString("tried_decrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified error processing file.
        /// </summary>
        internal static string unspecified_error_processing_file {
            get {
                return ResourceManager.GetString("unspecified_error_processing_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        internal static string usage {
            get {
                return ResourceManager.GetString("usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with errors.
        /// </summary>
        internal static string with_errors {
            get {
                return ResourceManager.GetString("with_errors", resourceCulture);
            }
        }
    }
}
